name: .NET Domestify Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Artifact
      run: dotnet publish -c Release -o ./publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./publish

  download-artifacts:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: ./downloaded-artifacts

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.5.0
      with:
        token: ${{ secrets.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 }}
        target: 'http://localhost:5000'
